RETROARCH_SERVICE_PARAMETERS = "-v -L atari800_libretro.so /home/retro/ROMs/atari5200/Pac-Man_Atari5200-cart.bin"

RETROARCH_SERVICE_FAILURE_ACTION = "reboot"
RETROARCH_SERVICE_SUCCESS_ACTION = "none"
